-- AlterTable
ALTER TABLE "Application" ADD COLUMN     "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "applicationStatus" SET DEFAULT 'PENDING',
ALTER COLUMN "computerSkills" SET DATA TYPE TEXT[];
